name: Deploy Create React App

on:
  push:
    branches:
      - master  # Укажите ветку, на которую будет происходить пуш

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Сборка приложения

      - name: Archive build artifacts
        run: |
          mkdir -p artifacts
          cp package.json artifacts/
          cp -r dist/* artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Зависимость от job'а сборки

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

      - name: Install sshpass
        run: sudo apt-get install -y sshpass  # Установка sshpass для использования пароля

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy files to server via SSH
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}       # Имя пользователя для SSH
          SERVER_IP: ${{ secrets.SERVER_IP }}           # IP-адрес сервера
          SERVER_PATH: ${{ secrets.SERVER_PATH }}       # Путь на сервере, куда будут копироваться файлы
          SERVER_PASSWORD: ${{ secrets.PASSWORD }} # Пароль для SSH
          DATABASE_CLIENT: mysql
          DATABASE_HOST: kuzovok11.beget.tech
          DATABASE_NAME: kuzovok11_fasady
          DATABASE_USERNAME: kuzovok11_fasady
          DATABASE_PASSWORD: 8!rcs!MvZa82
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz ./artifacts/ $SERVER_USER@$SERVER_IP:$SERVER_PATH

      - name: Install Dependencies on server
        run: |
          sshpass -e ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && \
            rm -rf node_modules/ package-lock.json"
          
          sshpass -e ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "cd ${{ secrets.SERVER_PATH }} && \
            npm config set prefix ~/.npm-global && \
            export PATH=~/.npm-global/bin:$PATH && \
            npm install --production"
          
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "cd ${{ secrets.SERVER_PATH }} && npm install --production"

      - name: Touch restart file
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
              "touch ${{ secrets.SERVER_PATH }}/tmp/restart.txt"
          

      - name: Clean up after deployment
        run: echo "Deployment completed successfully!"  # Сообщение о завершении развертывания
